[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[dependencies]
fantasmagorie = { path = "../fantasmagorie" }
winit = "0.29.15"
glutin = "0.32.1"
glutin-winit = "0.5.0"
glow = "0.14.0"
raw-window-handle = "0.6.2"
