[package]
name = "fantasmagorie"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.29.15"
glutin = "0.32.1"
glutin-winit = "0.5.0"
glow = "0.14.0"
raw-window-handle = "0.6.2"
ab_glyph = "0.2.28"
image = "0.25.2"
bitflags = "2.6.0"
thiserror = "1.0"
cfg-if = "1.0"
